language: java

jdk: oraclejdk11

before_install:
- chmod +x mvnw
- mvn -Djasypt.encryptor.password=$JASYPT_ENCRYPTOR_PASSWORD install


env:
  global:
  - secure: fzcuivTlgtdoVZT/EWkGruVORZWPE2euLqz1G2pnSbatWKNPFLsuEbW0FCTVRN31In/5VCUP/1KlFH7Dh7Ocw+o4u/Gfz0sMEVQlXP25j3Dk0mgjtZT6DVh7aZ520CndQcdTmvQtoU6jcT5wZVF18P1hy5N5ugq7Q3HyQEUdUwo5vLxf7qLzD/G0h/+p6UP8O5NNWIZS8sJzSeMSRbZ7FajElVZvjTQGdfpGtO3F3Ow8ZH4gwAc7ZzCCMGGLxGYPXVx0fjXLxQy1P4cEPPWf7ZAqutGxG892vf0R86bjBX/RHudHkHHGv5FCc1IvCpH6CarEoRyyH8/Wm4AC5dq5LYG2KkPJ7m2SOyFhYe23Xw4TFO7LTl/f0hMUkse2HJ1Rsuf1ezEa0LK9Rf72panq7vBW/RABXNy7bl7lKX6GQwe1tK/11nZRY2bRw7JKTt0lSl4eb3ZWLfTD4E5YUh+vW3ETlPbbnvFtkJlgtvA3fHbMORHj9Ku6KV6NUdAXL5A/VCYv5nmVd54jQJCirdZZmyUlQiBiXrqIa+VPe9Vn42N9cFSx9x8g1qVQ0UvpsdvisdSCpNVqGDhq0a/pcWDAZoqCKLXTF42up6htrEhSfhqi3WmPSxZAzEBlN8y1YTcvowczn7ZE4JMS+dSk7ff2pH5i6tGU5KrHfxTVa7IQOE4=
  - secure: iaZNAmt0MMZZSfO/3zpiehTVzjgboOjaHXSrgVTkybDuDk3RB1idxxAjD+/dGEiigqLSkwV/2d2Wwdim3FNFynIYCl/4Bw13S0fAEk7w4/pJu7Hi+frkeBJNadhwDq+Rxbe2cWBP9mrOBJCA50UR5Zr1HDjUvA4HICwmajo4cJAMV6WJW0CShxpMzezB9OEh1qxfbdS5kUcoKNv8Z8gZz081/yWlEKPELXNiTRE2GNsJLnloFuCtgL6204Bf1LfQP2LHgrpuLdbuNEYOHcRzUXGJCcY12xGoqhm4yKEnqkmnqh5U//P+BPrWYTVQmD/IJ/cy1eJLWp6conecPQ51VaU2ksM6dDYCViGbSlp7ZF8GfX0adtAraQJIxjzQMb21pbhMxVJUQnpsTBYUGM3hSaxI1VoL/mm5yAytqkE+JYGQzEUPprHwCl6+83oJ9PyOF/osDFeKHICyT4VusZbBqXTdktMuxhsT6Lv4NPLTWdk5pqygL1c1LeHY6BuWWJXX+s22beVY0nk275Cj/volcePfqBiynaZCS3OVNreNmxejLVr/pNadKixiUwDRrCWoy2LONi5JbLqW8n3BalwfVczYgxL55NkZbJeo2oGypjovQ6zNHhXJ/I99JvETPQyn1U1FPTBkQh+thGOrjdhMg14dXnMI3wUMc9q43JF0as4=
  - secure: tWwG/+kzj43LNGHQlbyeR+TCZlzSaH7dS6wN2e5SEwcDdXypynZBi1EVb1LaWZYeEvUbHtfYx/YRDTUlRXOFpYemWhKZ7oPJwerWppDFEpy9fwpCxYVOkPOnw/ES0zKwWwtHMUefOaO7vORoUdsIwtcPV5ScIROJxR886AVm5GYUemhTdUzpFmOiM9y00ozoSJzYUt7zZOgmvLQt3d7ENmqWvfWOp9gKMH5FFC+XoUGqgIyI/ORMoQtMhR0ItJi9tLDibwgIBiwoE651y5TbUm0l0o4/m1tCi2RJslmOjzQA1674qVboaccyXG6xQrmxPdv/J0FEB/J42ZRvobv9jA8X4HlR0qrwON3+9TyhplAYWRP+L6K2duz+hBOU51lUZVBu6orUCJjOf4DwyfGyUYv15s2/6YKQrKbFZETfK8ivHDIRsjp952If7FwfkGBaZvtT4OnNhcOhOhMMzYHCBv092KN2+8sPLNqfd+/brWiTxnJjTnfW6D8Yni45LwgWf7/XlJzguaQDBRqhF+N3/W/t6KENGTuoEUqEfBitgSmXFi0LzwlcYs4kxq7kn+aRqE7UcLExrRs7tuFtmEXi2sB14c37IEzcDYacWyUlzzrK95Gh3rn70/BhJwpShW/Rm/mQyoiyebtGQU5oJzOXEZ+JwZ+EI+IvPZMQsfnvSKc=

addons:
  sonarcloud:
    organization: k0siara-github
    token:
      secure: "$SONAR_TOKEN"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: todo-spring-java
