language: java

jdk:
  - oraclejdk11

before_install:
  - chmod +x mvnw

env:
  global:
    secure: fzcuivTlgtdoVZT/EWkGruVORZWPE2euLqz1G2pnSbatWKNPFLsuEbW0FCTVRN31In/5VCUP/1KlFH7Dh7Ocw+o4u/Gfz0sMEVQlXP25j3Dk0mgjtZT6DVh7aZ520CndQcdTmvQtoU6jcT5wZVF18P1hy5N5ugq7Q3HyQEUdUwo5vLxf7qLzD/G0h/+p6UP8O5NNWIZS8sJzSeMSRbZ7FajElVZvjTQGdfpGtO3F3Ow8ZH4gwAc7ZzCCMGGLxGYPXVx0fjXLxQy1P4cEPPWf7ZAqutGxG892vf0R86bjBX/RHudHkHHGv5FCc1IvCpH6CarEoRyyH8/Wm4AC5dq5LYG2KkPJ7m2SOyFhYe23Xw4TFO7LTl/f0hMUkse2HJ1Rsuf1ezEa0LK9Rf72panq7vBW/RABXNy7bl7lKX6GQwe1tK/11nZRY2bRw7JKTt0lSl4eb3ZWLfTD4E5YUh+vW3ETlPbbnvFtkJlgtvA3fHbMORHj9Ku6KV6NUdAXL5A/VCYv5nmVd54jQJCirdZZmyUlQiBiXrqIa+VPe9Vn42N9cFSx9x8g1qVQ0UvpsdvisdSCpNVqGDhq0a/pcWDAZoqCKLXTF42up6htrEhSfhqi3WmPSxZAzEBlN8y1YTcvowczn7ZE4JMS+dSk7ff2pH5i6tGU5KrHfxTVa7IQOE4=

addons:
  sonarcloud:
    organization: k0siara-github
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

