server:
  jackson:
    serialization:
      indent-output: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.patrykkosieradzki.todo: debug

db:
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
  driver: org.postgresql.Driver