spring:
  profiles.active: dev
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  resources:
    add-mappings: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.patrykkosieradzki.todo: debug

vaadin:
  productionMode: true


mail:
  host: SMTP.office365.com
  username: ENC(3kgJyu6PoTk/Kfy0YHdWojEScWbBU5Pi6O8e3qrwnS+72iwTqB83RA==)
  password: ENC(PSq5a6TnJLwKznCLqIJo7XPSYSuo0im3)
  port: 587



