CREATE TABLE users(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	username varchar(255) unique not null,
	email varchar(255) unique not null,
	password varchar(255) not null
);